sudo: true
dist: trusty
jobs:
  include:
  - stage: build docker image
    script:
    - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
    - docker build -t travis-ci-build-stages-demo .
    - docker images
    - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/travis-ci-build-stages-demo
    - docker push $DOCKER_USERNAME/travis-ci-build-stages-demo
  - stage: test
    script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt
  - script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt
env:
  global:
  - secure: cyb78WyCt95LChkl8LIfgrkpGwAOduZlbF5TBPypcu3lIXAeYnYAt4KL7OGAcxuMUmdaB8UiZVqF6m5vDMDntvxXUBYJf36fRbSajXFGsCtzBzsxsyUnWgk3XX9LtL05L0j2vj3dGmYryd4zfTtg8tqpE5tD6tvc94OtIVcjlBUiaBSy+7rHED++gxLI7A+jH5n8+dzdFPJy+WRsZOFBzAVazLE6TcrmWtrVNwViPWx2xuWijyxGx9FULkiIW45I7QU8jWQCpj7RdmaeThOJ1eJtHcbJlqXI4fZWmJqwSlcSxGAsnUYIZsExRZxo7NRj/kWBPwRTz1CaBxwrPcXdmJKZCSOqHczRj/7AM+c3mexvEvnLsAGjX2fXON2rT1Ma0NSIvXEc6hwudVhnVw+2D8GK9k8MoHhOneyqrmYoYNigIfysr9Y9V1Z+nq8+IKgGm1foy3e/bFqUV+WYM9Xd9NvktKIIELERYmFfKC2I4VviyvgcKdwphjWR96SloWH8GqZacrTTHIV1mY2PB2qVbYGLQIhqGXqmA68FYqqqNbv58EF1fDqeDfR58x1/4s1ShONp2HY/Wh9M8MlcJ5s0i4qKtTs+Tdom6dIGzvb9fswVFAwnJwbOOONWelHkWb5k1Y/E1ef2HFZJ5dSMse5eHGaYE/WRhOQLfUl7BS75zsw=
  - secure: XxOkCqmDYlbi3wMpXWJqsaxEnYTcCi91Y6ibTDrvvkirc5sdhvNNIXXJ7hc4kOiMhYBEEJSR+Bq+McuAFqoMe3lC+rTP8qZWgvrc+MW9FoNpjmSAhg0ppToqBfC1PGVKHayH2dAsy8hWij4mfH7s1hPGx+JsX8rC/cisRWCASuCpDsDksL8RxwbuY3qY85KG534Z+is+gAAOSznp5CYPhTjv26FaQKLqcF75TcflgElii2FGO775Jem4Cr3X9fskCQQ4d0xslOrfHn5mk650RjlTQwGm1rK9Be/XaB400kUqGLWFNjktIeb2az7W0WCh1rpsqmNHig7IK4I2EPwzpKrb+eGK1dnK+ssLGckhlFJ09sN4w35Wmz3iL4bnLmbEGy54VewQ6DHXn9rhGpmywsuIU/HO5FVRMFQ7GtjCsMzei7OMDF4ej1r0hf3dL1o+YMEvpjUrMs69prtX70HqHGZKbDv/zZlsXywS8uvLt5ylZelm/lI6sle19FYerYBGFtra3z3k17PMuDtdwValz+MoaJoHi6aJ6JLiFDU8ioqfq2sAAibsRZLu4LfdfuMWV5eBZ9J7NKRN0LdSOjxphKn2R2CAidH+lcP7Zr/msCAlo37eoNMttdq3wt4n4SlAkPMr4KRXswA36N52e1DNBoV/a2sBZHlLFZN8vr9sDQQ=
